# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  # boot.initrd.kernelModules = [];
  # boot.kernelParams = ["i915.force_probe=46a8"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/844c0515-0571-4c57-b60d-0e2bfd294264";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  boot.initrd.luks.devices."luks-9d5e10ca-5ae6-40f4-b4a0-9bb44251078f".device = "/dev/disk/by-uuid/9d5e10ca-5ae6-40f4-b4a0-9bb44251078f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EF08-61F9";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/21d40978-65fb-44be-b380-61d8d07a98fa";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-67869d5f-9474-4260-8093-4132020c8ef5".device = "/dev/disk/by-uuid/67869d5f-9474-4260-8093-4132020c8ef5";

  # swapDevices removed: referenced device 3bb16aea-a477-4605-b564-75ab57a63af8
  # no longer exists / should not be used.
  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  hardware.graphics = {
    enable = true;
    # driSupport = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver # VAAPI driver
      intel-compute-runtime # OpenCL support
      intel-vaapi-driver
      libva-vdpau-driver
      # vaapiIntel # Older but sometimes more stable VAAPI driver
      # vaapiVdpau # VAAPI-VDPAU bridge
      libvdpau-va-gl # VDPAU bridge
    ];
  };

  # Make sure you're in the video group
  users.users.felipe.extraGroups = ["video"];

  # Load Intel graphics module early
  boot.initrd.kernelModules = ["i915"];

  # Enable hardware acceleration features
  boot.kernelParams = [
    "i915.enable_guc=2" # Enable GuC firmware for better performance
    "i915.enable_fbc=1" # Enable frame buffer compression
    "i915.fastboot=1" # Faster display initialization
    "intel_pstate=active" # Ensure Intel P-State driver is active
  ];
}
