{
  config,
  pkgs,
  lib,
  ...
}: {
  # Gitleaks — block commits containing secrets before they hit history
  home.packages = [pkgs.gitleaks];

  # Global git template with pre-commit hook
  # All new repos automatically get the hook via init.templateDir.
  # Existing repos can run: git init (safe, re-inits hooks)
  home.file.".git-templates/hooks/pre-commit" = {
    executable = true;
    text = ''
      #!/bin/sh
      # Auto-generated by home-manager — gitleaks pre-commit hook
      # Blocks commits if staged changes contain secret patterns.

      set -e

      if ! command -v gitleaks >/dev/null 2>&1; then
        echo "warning: gitleaks not found in PATH; skipping secret scan"
        exit 0
      fi

      if command -v alejandra >/dev/null 2>&1; then
        if ! alejandra --check . >/dev/null 2>&1; then
          echo "❌ alejandra: nix files are not formatted. Run 'alejandra .'"
          exit 1
        fi
      fi

      echo "🔒 gitleaks: scanning staged changes for secrets..."
      gitleaks protect --verbose --redact --staged
      echo "✅ gitleaks: no secrets detected"
    '';
  };

  # Ensure git uses the global template for all new repositories
  programs.git = {
    enable = true;
    settings = {
      init.templateDir = "${config.home.homeDirectory}/.git-templates";
    };
  };
}
