{
  config,
  pkgs,
  lib,
  ...
}:
with lib; let
  cfg = config.semi-active-av;
  sus-user-dirs = [
    "Downloads"
    ".mozilla"
  ];
  all-normal-users = attrsets.filterAttrs (username: config: config.isNormalUser) config.users.users;
  all-sus-dirs =
    builtins.concatMap (
      dir:
        attrsets.mapAttrsToList
        (username: config: config.home + "/" + dir)
        all-normal-users
    )
    sus-user-dirs;
  all-user-folders = attrsets.mapAttrsToList (username: config: config.home) all-normal-users;
  all-system-folders = [
    "/boot"
    "/etc"
    "/nix"
    "/opt"
    "/root"
    "/usr"
  ];
  notify-all-users =
    pkgs.writeScript "notify-all-users-of-sus-file"
    ''
      #!/bin/sh
      ALERT="Signature detected by clamav: $CLAM_VIRUSEVENT_VIRUSNAME in $CLAM_VIRUSEVENT_FILENAME"
      # Send an alert to all graphical users.
      for ADDRESS in /run/user/*; do
          USERID=''${ADDRESS#/run/user/}
         /run/wrappers/bin/sudo -u "#$USERID" DBUS_SESSION_BUS_ADDRESS="unix:path=$ADDRESS/bus" ${pkgs.libnotify}/bin/notify-send -i dialog-warning "Sus file" "$ALERT"
      done
    '';
in {
  options = {
    semi-active-av = {
      enable = mkOption {
        type = types.bool;
        default = false;
      };
    };
  };

  config = mkIf cfg.enable {
    security.sudo = {
      extraConfig = ''
        clamav ALL = (ALL) NOPASSWD: SETENV: ${pkgs.libnotify}/bin/notify-send
      '';
    };

    services.clamav.daemon = {
      enable = true;

      settings = {
        # Ensure a predictable clamd local socket path and permissions
        LocalSocket = "/run/clamav/clamd.ctl";
        LocalSocketMode = "666";
        FixStaleSocket = true;
        OnAccessIncludePath = all-sus-dirs;
        OnAccessPrevention = false;
        OnAccessExtraScanning = true;
        OnAccessExcludeUname = "clamav";
        VirusEvent = "${notify-all-users}";
        User = "clamav";
      };
    };
    services.clamav.updater.enable = true;

    systemd.services.clamav-clamonacc = {
      description = "ClamAV daemon (clamonacc)";
      after = ["clamav-daemon.service" "clamav-freshclam.service"];
      requires = ["clamav-daemon.service"];
      wantedBy = ["multi-user.target"];
      restartTriggers = [
        "/etc/clamav/clamd.conf"
        "/etc/clamav/clamonacc.conf"
        "/etc/clamav/clamonacc-watchlist.txt"
      ];

      serviceConfig = {
        Type = "simple";
        # Wait for clamd and point clamonacc at explicit config + watch list
        ExecStart = "${pkgs.systemd}/bin/systemd-cat --identifier=av-scan ${pkgs.clamav}/bin/clamonacc -F --fdpass --wait --config-file=/etc/clamav/clamonacc.conf --watch-list=/etc/clamav/clamonacc-watchlist.txt";
        PrivateTmp = "yes";
        PrivateDevices = "yes";
        PrivateNetwork = "yes";
        Restart = "on-failure";
        RestartSec = "5s";
      };
    };

    # clamonacc configuration: ensure it connects to clamd via local socket
    environment.etc."clamav/clamonacc.conf".text = ''
      # Generated by semi-active-av module
      ClamdSocket unix:/run/clamav/clamd.ctl
      ExcludeUname clamav
    '';

    # Watch list for on-access scanner (user Download + mozilla dirs)
    environment.etc."clamav/clamonacc-watchlist.txt".text = lib.concatStringsSep "\n" all-sus-dirs + "\n";

    systemd.timers.av-user-scan = {
      description = "scan normal user directories for suspect files";
      wantedBy = ["timers.target"];
      timerConfig = {
        OnCalendar = "weekly";
        Unit = "av-user-scan.service";
      };
    };

    systemd.services.av-user-scan = {
      description = "scan normal user directories for suspect files";
      after = ["network-online.target"];
      wants = ["network-online.target"];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${pkgs.systemd}/bin/systemd-cat --identifier=av-scan ${pkgs.clamav}/bin/clamdscan --quiet --recursive --fdpass ${toString all-user-folders}";
      };
    };

    systemd.timers.av-all-scan = {
      description = "scan all directories for suspect files";
      wantedBy = ["timers.target"];
      timerConfig = {
        OnCalendar = "monthly";
        Unit = "av-all-scan.service";
      };
    };

    systemd.services.av-all-scan = {
      description = "scan all directories for suspect files";
      after = ["network-online.target"];
      wants = ["network-online.target"];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = ''
          ${pkgs.systemd}/bin/systemd-cat --identifier=av-scan ${pkgs.clamav}/bin/clamdscan --quiet --recursive --fdpass ${toString all-system-folders}
        '';
      };
    };
  };
}
